from normalization.normalizer import Normalizer

currency_mapping = {
    "$": "US Dollar",
    "USD": "US Dollar",
    "£": "British Pound",
    "GBP": "British Pound",
    "€": "Euro",
    "EUR": "Euro",
    "¥": "Japanese Yen",
    "JPY": "Japanese Yen",
    "₹": "Indian Rupee",
    "INR": "Indian Rupee",
    "C$": "Canadian Dollar",
    "CAD": "Canadian Dollar",
    "A$": "Australian Dollar",
    "AUD": "Australian Dollar",
    "CHF": "Swiss Franc",
    "Swiss Franc": "Swiss Franc",
    "CN¥": "Chinese Yuan",
    "CNY": "Chinese Yuan",
    "SGD": "Singapore Dollar",
    "Singapore Dollar": "Singapore Dollar",
    "NZ$": "New Zealand Dollar",
    "NZD": "New Zealand Dollar",
    "HK$": "Hong Kong Dollar",
    "HKD": "Hong Kong Dollar",
    "SEK": "Swedish Krona",
    "Swedish Krona": "Swedish Krona",
    "NOK": "Norwegian Krone",
    "Norwegian Krone": "Norwegian Krone",
    "₩": "South Korean Won",
    "KRW": "South Korean Won",
    "MX$": "Mexican Peso",
    "MXN": "Mexican Peso",
    "R$": "Brazilian Real",
    "BRL": "Brazilian Real",
    "TRY": "Turkish Lira",
    "Turkish Lira": "Turkish Lira",
    "ZAR": "South African Rand",
    "South African Rand": "South African Rand",
    "IDR": "Indonesian Rupiah",
    "Indonesian Rupiah": "Indonesian Rupiah",
    "MYR": "Malaysian Ringgit",
    "Malaysian Ringgit": "Malaysian Ringgit",
    "PHP": "Philippine Peso",
    "Philippine Peso": "Philippine Peso",
    "THB": "Thai Baht",
    "Thai Baht": "Thai Baht",
    "HUF": "Hungarian Forint",
    "Hungarian Forint": "Hungarian Forint",
    "CZK": "Czech Koruna",
    "Czech Koruna": "Czech Koruna",
    "ILS": "Israeli New Shekel",
    "Israeli New Shekel": "Israeli New Shekel",
    "PLN": "Polish Złoty",
    "Polish Złoty": "Polish Złoty",
    "DKK": "Danish Krone",
    "Danish Krone": "Danish Krone",
    "AED": "United Arab Emirates Dirham",
    "United Arab Emirates Dirham": "United Arab Emirates Dirham",
    "SAR": "Saudi Riyal",
    "Saudi Riyal": "Saudi Riyal",
    "RON": "Romanian Leu",
    "Romanian Leu": "Romanian Leu",
    "RUB": "Russian Ruble",
    "Russian Ruble": "Russian Ruble",
    "CLP": "Chilean Peso",
    "Chilean Peso": "Chilean Peso",
    "TWD": "New Taiwan Dollar",
    "New Taiwan Dollar": "New Taiwan Dollar",
    "ARS": "Argentine Peso",
    "Argentine Peso": "Argentine Peso",
    "COP": "Colombian Peso",
    "Colombian Peso": "Colombian Peso",
    "VND": "Vietnamese Đồng",
    "Vietnamese Đồng": "Vietnamese Đồng",
    "NGN": "Nigerian Naira",
    "Nigerian Naira": "Nigerian Naira",
    "UAH": "Ukrainian Hryvnia",
    "Ukrainian Hryvnia": "Ukrainian Hryvnia",
    "EGP": "Egyptian Pound",
    "Egyptian Pound": "Egyptian Pound",
    "QAR": "Qatari Riyal",
    "Qatari Riyal": "Qatari Riyal",
    "BDT": "Bangladeshi Taka",
    "Bangladeshi Taka": "Bangladeshi Taka",
    "PKR": "Pakistani Rupee",
    "Pakistani Rupee": "Pakistani Rupee",
    "PEN": "Peruvian Sol",
    "Peruvian Sol": "Peruvian Sol"
}


class CurrencyNorm(Normalizer):
    def __init__(self,lookups:dict=None):
        super().__init__()
        if not lookups:
            self.lookups = currency_mapping
        else:
            self.lookups = lookups
        
    def process(self,text):
        return self.lookups[text]
                